[package]
name = "katal"
version = "0.0.1"
authors = ["Trinkler Software <company@trinkler.software>"]
build = "build.rs"
edition = "2018"

[[bin]]
name = "katal"
path = "node/src/main.rs"

# Rust crates
[dependencies.derive_more]
version = "0.14.0"

[dependencies.futures]
version = "0.1"

[dependencies.log]
version = "0.4"

[dependencies.tokio]
version = "0.1"

[dependencies.exit-future]
version = "0.1"

[dependencies.parking_lot]
version = "0.8.0"

[dependencies.trie-root]
version = "0.12.2"

[dependencies.parity-codec]
version = "3.3"

[dependencies.ctrlc]
version = "3.1.3"
features = ["termination"]

# Substrate Core crates
[dependencies.sr-io]
git = "https://github.com/paritytech/substrate.git"
rev = "dbf3226"

[dependencies.primitives]
package = "substrate-primitives"
git = "https://github.com/paritytech/substrate.git"
rev = "dbf3226"

[dependencies.substrate-client]
git = "https://github.com/paritytech/substrate.git"
rev = "dbf3226"

[dependencies.consensus]
package = "substrate-consensus-aura"
git = "https://github.com/paritytech/substrate.git"
rev = "dbf3226"

[dependencies.substrate-cli]
git = "https://github.com/paritytech/substrate.git"
rev = "dbf3226"

[dependencies.substrate-executor]
git = "https://github.com/paritytech/substrate.git"
rev = "dbf3226"

[dependencies.substrate-service]
git = "https://github.com/paritytech/substrate.git"
rev = "dbf3226"

[dependencies.inherents]
package = "substrate-inherents"
git = "https://github.com/paritytech/substrate.git"
rev = "dbf3226"

[dependencies.transaction-pool]
package = "substrate-transaction-pool"
git = "https://github.com/paritytech/substrate.git"
rev = "dbf3226"

[dependencies.network]
package = "substrate-network"
git = "https://github.com/paritytech/substrate.git"
rev = "dbf3226"

[dependencies.basic-authorship]
package = "substrate-basic-authorship"
git = "https://github.com/paritytech/substrate.git"
rev = "dbf3226"

[dependencies.katal-runtime]
path = "node/runtime"

[build-dependencies]
vergen = "3"
