[package]
name = "modules-structures"
version = "1.0.0"
authors = ["Trinkler Software <company@trinkler.software>"]
edition = "2018"

[features]
default = ["std"]
std = [
	"serde",
	"parity-codec/std",
	"runtime_std/std",
]

# Rust crates
[dependencies.serde]
version = "1.0"
optional = true

[dependencies.parity-codec]
version = "3.5"
default-features = false
features = ["derive"]

# Substrate Core crates
[dependencies.runtime_std]
package = "sr-std"
git = "https://github.com/paritytech/substrate.git"
branch = "v1.0"
default-features = false

# Debug crates
[dev-dependencies.rand]
version = "0.7"
